# Generated by Django 3.0.8 on 2020-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
