# Generated by Django 3.0.8 on 2020-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Desc',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
