# Generated by Django 3.0.8 on 2020-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200807_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('no_room', models.IntegerField()),
                ('kitchen', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('adress', models.TextField()),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.IntegerField()),
                ('rent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
