# Generated by Django 3.0.8 on 2020-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200807_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='room_pics'),
        ),
    ]
