# Generated by Django 3.0.8 on 2020-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_room_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='room',
            name='img2',
            field=models.ImageField(default='', upload_to='room_pics'),
        ),
        migrations.AddField(
            model_name='room',
            name='img3',
            field=models.ImageField(default='', upload_to='room_pics'),
        ),
        migrations.AddField(
            model_name='room',
            name='img4',
            field=models.ImageField(default='', upload_to='room_pics'),
        ),
    ]
