# Generated by Django 3.0.8 on 2020-08-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200807_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to='room_pics'),
        ),
        migrations.AlterField(
            model_name='room',
            name='img3',
            field=models.ImageField(default='default.jpg', upload_to='room_pics'),
        ),
        migrations.AlterField(
            model_name='room',
            name='img4',
            field=models.ImageField(default='default.jpg', upload_to='room_pics'),
        ),
    ]
