# Generated by Django 3.0.8 on 2020-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200807_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img4',
            field=models.ImageField(default='default_room.jpg', upload_to='room_pics'),
        ),
    ]
