# Generated by Django 3.0.8 on 2020-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200813_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner_phone',
            field=models.CharField(max_length=50),
        ),
    ]
